---
title: "surveys ggplot"
author: "Brian S Yandell"
date: "October 12, 2016"
output:
  html_notebook: default
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Preliminaries

Load libraries. `date` is `r date()`

```{r library, echo=FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
```

Load data.

```{r load_data}
surveys <- read.csv("data/portal_data_joined.csv")
```

Clean data.

```{r clean_data}
surveys_complete <- surveys %>%
  filter(species_id != "", !is.na(weight)) %>%
  filter(!is.na(hindfoot_length), sex != "")
# count records per species
species_counts <- surveys_complete %>%
  group_by(species_id) %>%
  tally
# get names of the species with counts >= 10
frequent_species <-  species_counts %>%
  filter(n >= 10) %>%
  select(species_id)
# filter out the less-frequent species
surveys_complete <- surveys_complete %>%
  filter(species_id %in% frequent_species$species_id)
```

## Plot weight by hindfoot length

```{r}
ggplot(surveys_complete %>%
         filter(species_id == "DM"), 
       aes(x = weight, y = hindfoot_length)) + 
  geom_point(shape = 1)
```

